application:
  - name:  "parseable-operator"
    namespace: parseable-operator
    chartName: "kube-state-metrics"
    repoName: "prometheus-community"
    repoUrl: "https://prometheus-community.github.io/helm-charts"
    version: "5.18.0"
    values:
     - tolerations[0].key=app
     - tolerations[0].operator=Equal
     - tolerations[0].value=system
     - tolerations[0].effect=NoSchedule
