apiVersion: datainfra.io/v1
kind: Applications
metadata:
  name: ws1-fooya-parseable
  namespace: fooya
spec:
  dataplane: aws-us-east-1-iiwx
  tenant: ws1-fooya
  applications:
  - name: zookeeper-operator
    spec:
      chartName: "zookeeper-operator"
      repoName: "pravega"
      repoUrl: "https://charts.pravega.io"
      version: "0.2.15"
  - name: druid-operator
    spec:
      chartName: "druid-operator"
      repoName: "datainfra"
      repoUrl: "https://charts.datainfra.io"
      version: "0.3.1"
  - name: zookeeper-ws-analytics
    spec:
      chartName: "zookeeper"
      repoName: "pravega"
      repoUrl: "https://charts.pravega.io"
      version: "0.2.15"
