apiVersion: datainfra.io/v1
kind: Applications
metadata:
  name: shared-saas
  namespace: parseable
spec:
  envRef: shared-aws-us-east-1-flge
  applications:
  - name: zookeeper-operator
    scope: environment # single operator can reconcile multiple environments
    spec:
      chartName: "zookeeper-operator"
      repoName: "pravega"
      repoUrl: "https://charts.pravega.io"
      version: "0.2.15"
  - name: druid-operator
    scope: environment
    spec:
      chartName: "druid-operator"
      repoName: "datainfra"
      repoUrl: "https://charts.datainfra.io"
      version: "0.3.1"
  - name: zookeeper-ws-analytics
    scope: tenant 
    tenant: parseables # name of tenant
    spec:
      chartName: "zookeeper"
      repoName: "pravega"
      repoUrl: "https://charts.pravega.io"
      version: "0.2.15"
