application:
  - name:  "customer1"
    namespace: ws2-customer1
    chartName: "chi"
    repoName: datainfra
    repoUrl: https://charts.datainfra.io
    version: 0.0.4
    values: 
     - replicas=1
     - shared=3
