apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pb
rules:
- apiGroups:
  - datainfra.io
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - datainfra.io
  resources:
  - dataplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - configmaps
  - namespaces
  - serviceaccounts
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pb
subjects:
- kind: ServiceAccount
  name: parseable
  namespace: parseable
