apiVersion: datainfra.io/v1
kind: Application
metadata:
  labels:
    app: ballastdata
    env: druid
  name: datainfra
  namespace: demo
spec:
  envRef: dataplaform
  applications:
    zookeeper-operator:
      scope: environment # single operator can reconcile multiple environments
      spec:
        chartName: "zookeeper-operator"
        repoName: "pravega"
        repoUrl: "https://charts.pravega.io"
        version: "0.2.15"
    druid-operator:
      scope: environment
      spec:
        chartName: "druid-operator"
        repoName: "datainfra"
        repoUrl: "https://charts.datainfra.io"
        version: "0.3.1"
    parseable-operator:
      scope: environment
      spec:
        chartName: "operator"
        repoName: "parseable"
        repoUrl: "https://charts.parseable.io"
        version: "0.0.3"
    vector-agent:
      scope: environment
      spec:
        chartName: "vector"
        repoName: "vector"
        repoUrl: "https://helm.vector.dev"
        version: "0.22.1"
    nginx-ingress:
      scope: environment
      spec:
        chartName: "ingress-nginx"
        repoName: "ingress-nginx"
        repoUrl: "https://kubernetes.github.io/ingress-nginx"
        version: "1.8.0"
    zookeeper-ws-analytics: # name of application
      scope: tenant 
      tenant: workspace-analytics # name of tenant
      appType: zookeeper # application type
      spec:
        chartName: "zookeeper"
        repoName: "pravega"
        repoUrl: "https://charts.pravega.io"
        version: "0.2.15"
        values: 
         - pod.nodeSelector.app=zk 
         - pod.tolerations[0].key=application
         - pod.tolerations[0].operator=Equal
         - pod.tolerations[0].value=workspace-analytics-zookeeper-zk-small-zookeeper
         - pod.tolerations[0].effect=NoSchedule
