apiVersion: datainfra.io/v1
kind: Application
metadata:
  labels:
    app: ballastdata
    env: druid
  name: datainfra
  namespace: demo
spec:
  envRef: datainfra
  applications:
    zookeeper-operator:
      scope: environment
      spec:
        chartName: "zookeeper-operator"
        repoName: "pravega"
        repoUrl: "https://charts.pravega.io"
        version: "0.2.15"
    zookeeper-custom-resource: # name of application
      scope: tenant 
      tenant: workspace-analytics # name of tenant
      appType: zookeeper # application type
      spec:
        chartName: "zookeeper"
        repoName: "pravega"
        repoUrl: "https://charts.pravega.io"
        version: "0.2.15"
        values: 
         - pod.nodeSelector.app=zk 
         - pod.tolerations[0].key=application
         - pod.tolerations[0].operator=Equal
         - pod.tolerations[0].value=workspace-analytics-zookeeper-zookeepernodes # {{ tenantname }}-{{ apptype }}-{{ ngnodename }}
         - pod.tolerations[0].effect=NoSchedule
