apiVersion: datainfra.io/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: ballastdata
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ballastdata
  name: environment-dev
  namespace: demo
spec:
  envType: dev
  cloudInfra:
    type: aws
    awsRegion: us-east-1
    authSecretRef:
      secretName: aws-secret
      accessKeyName: accessKey
      secretKeyName: secretKey
    eks:
      name: dev-eks
      subnetIds:
      - subnet-0f4ecdb3695b63a0c
      - subnet-0ce931c60379fd4eb
      securityGroupIds:
      - sg-049b9e990b8a8e35f
      roleArn: "arn:aws:iam::437639712640:role/pulak-eks-role"
      version: "1.25"
  application:
    - name: clickhouse-datascience
      appType: ClickHouse
      size: clickhouse-small
    - name: clickhouse-new
      appType: ClickHouse
      size: clickhouse-medium
  size:
    - name: clickhouse-small
      spec:
        appType: ClickHouse
        nodes:
          nodeLabels:
            app: clickhouse
          nodeSize: t2.small
          min: 1
          max: 3
    - name: clickhouse-medium
      spec:
        appType: ClickHouse
        nodes:
          nodeLabels:
            app: clickhouse
          nodeSize: t2.medium
          min: 1
          max: 3
