apiVersion: datainfra.io/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: ballastdata
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ballastdata
  name: environment-dev
  namespace: demo
spec:
  envType: dev
  cloudInfra:
    type: aws
    awsRegion: us-west-2
    authSecretRef:
      secretName: aws-secret
      accessKeyName: accessKey
      secretKeyName: secretKey
    eks:
      name: dev-eks
      subnetIds:
      - subnet-0082133989e9658a2
      - subnet-0b947b189519a4131
      securityGroupIds:
      - sg-0f73e8dae6f8e61a8
      - sg-00363b093ce9ad413
      roleArn: "arn:aws:iam::437639712640:role/terraform-eks-demo-cluster"
      version: "1.25"
  application:
    - name: clickhouse-datascience
      appType: ClickHouse
      size: clickhouse-small
  size:
    - name: clickhouse-small
      spec:
        appType: ClickHouse
        nodes:
          nodeLabels:
            app: clickhouse
          nodeSize: t2.medium
          min: 1
          max: 3
