apiVersion: datainfra.io/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: ballastdata
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ballastdata
  name: environment-dev
  namespace: demo
spec:
  envType: dev
  cloudInfra:
    type: aws
    awsRegion: us-east-1
    authSecretRef:
      secretName: aws-secret
      accessKeyName: accessKey
      secretKeyName: secretKey
    eks:
      name: dev-eks-pulak
      subnetIds:
      - subnet-0dafc6c1dbdec3cd8
      - subnet-02952bc502311285b
      securityGroupIds:
      - sg-07841b20dd2180cc4
      roleArn: "arn:aws:iam::437639712640:role/pulak-eks-role"
      version: "1.25"
  application:
    - name: clickhouse-datascience
      appType: ClickHouse
      size: clickhouse-small
  size:
    - name: clickhouse-small
      spec:
        appType: ClickHouse
        nodes:
          nodeLabels:
            app: clickhouse
          nodeSize: t2.small
          min: 1
          max: 3
