apiVersion: datainfra.io/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: ballastdata
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ballastdata
  name: environment-dev
spec:
  envType: dev
  cloudInfra:
    type: aws
    awsRegion: us-west-2
    auth: 
      awsAccessKey: AKIAWLZK4B6AFWEZHDEO
      awsSecretAccessKey: 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
    eks:
      name: dev-eks
      subnetIds:
      - subnet-0ead63d54bf9ace41
      - subnet-02606e97a084174a4
      securityGroupIds:
      - sg-07d35cfe67eda9a63
      roleArn: "arn:aws:iam::437639712640:role/myAmazonEKSClusterRole"
      version: "1.22"
