apiVersion: datainfra.io/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: ballastdata
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ballastdata
  name: environment-dev
  namespace: demo
spec:
  envType: dev
  cloudInfra:
    type: aws
    awsRegion: us-east-1
    auth: 
      awsAccessKey: AKIAWLZK4B6ACNA3H43S
      awsSecretAccessKey: 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
    eks:
      name: dev-eks
      subnetIds:
      - subnet-0f4ecdb3695b63a0c
      - subnet-0ce931c60379fd4eb
      securityGroupIds:
      - sg-0c7a522c8ce4b82be
      roleArn: "arn:aws:iam::437639712640:role/pulak-eks-role"
      version: "1.22"
  application:
    - name: clickhouse-datascience
      appType: ClickHouse
      size: clickhouse-small
  size:
    - name: clickhouse-small
      spec:
        appType: ClickHouse
        nodes:
          nodeLabels:
            app: clickhouse
          nodeSize: t2.small
          min: 1
          max: 3
