apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.customer.name }}
  {{- range $key, $value := .Values.customer.labels }}
  labels:
      {{ $key }}: {{ $value }}
  {{- end }}
rules:
- apiGroups:
  - datainfra.io
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - datainfra.io
  resources:
  - dataplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - configmaps
  - namespaces
  - serviceaccounts
  - clusterrolebindings
  verbs: ["*"]
