apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.customer.name }}
  {{- range $key, $value := .Values.customer.labels }}
  labels:
      {{ $key }}: {{ $value }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.customer.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.customer.name }}
  namespace: {{ .Release.Namespace }}
