apiVersion: v1
kind: Secret
metadata:
  annotations:
      kubernetes.io/service-account.name: {{ .Values.customer.name }}
  name: {{ .Values.customer.name }}
  namespace: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.customer.labels }}
  labels:
      {{ $key }}: {{ $value }}
  {{- end }}
type: kubernetes.io/service-account-token
