apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.customer.name }}
  namespace:  {{ .Release.Namespace }}
  {{- range $key, $value := .Values.customer.labels }}
  labels:
      {{ $key }}: {{ $value }}
  {{- end }}
