application:
  - name:  "parseable-operator"
    namespace: parseable-operator
    chartName: "operator"
    repoName: "parseable"
    repoUrl: "https://charts.parseable.io"
    version: "0.0.2"
    values:
     - tolerations[0].key=app
     - tolerations[0].operator=Equal
     - tolerations[0].value=system
     - tolerations[0].effect=NoSchedule
