application:
  - name: parseable-cr
    chartName: parseable
    repoName: datainfra
    repoUrl: https://charts.datainfra.io
    version: 0.0.1
    values:
    - nodeSelector.size=medium
    - tolerations[0].key=application
    - tolerations[0].operator=Equal
    - tolerations[0].value=parseable-medium-parseable-server
    - tolerations[0].effect=NoSchedule